x=linspace(0,2*pi,60);
y=sin(x);
hf=figure('Color',[0,1,0],'Position',[1,1,450,250],...
         'Name','我的图形窗口','NumberTitle','off','MenuBar','none',...
         'KeyPressFcn', 'plot(x,y);axis([0,2*pi,-1,1]);');
